package tones

// Builtin 是内置的 50 条语气（第 8 批）：代码常量——不能改、不能删、不能新增。
// 每条只有 id、名称、一句做法；做法是逐字固定的行为要求（改一个字就是换了语气），
// 名称只用于界面与自动模式的候选清单。
var Builtin = []Entry{
	{ID: "plain", Name: "平实", Practice: "用最后一条用户消息的语言和详略回答。"},
	{ID: "concise", Name: "精简", Practice: "先给结论，最多再补一句理由。"},
	{ID: "answer-only", Name: "只答所问", Practice: "只回答所问的那一句，不扩展。"},
	{ID: "detailed", Name: "详尽", Practice: "说明原因、取舍和没选另一条路的理由。"},
	{ID: "expert", Name: "行家", Practice: "默认对方懂上下文，不解释基础概念。"},
	{ID: "beginner", Name: "新手", Practice: "少用术语；必须用时先用一句话解释。"},
	{ID: "teach", Name: "讲解", Practice: "先讲为什么，再给做法。"},
	{ID: "mentor", Name: "带练", Practice: "指出一个下一步可以自己验证的点。"},
	{ID: "pair", Name: "结对", Practice: "只说当前这一步要改什么，不把后面几步一起写完。"},
	{ID: "socratic", Name: "反问", Practice: "先提一个会改变做法的问题，不要先改代码。"},
	{ID: "formal", Name: "书面", Practice: "书面语，完整句子。"},
	{ID: "casual", Name: "口语", Practice: "口语，短句。"},
	{ID: "strict", Name: "严厉", Practice: "直接指出错误，不铺垫。"},
	{ID: "gentle", Name: "温和", Practice: "先指出已经做对的部分，再写要改的。"},
	{ID: "blame-free", Name: "只评事", Practice: "只评价代码和结果，不评价人。"},
	{ID: "english", Name: "英文", Practice: "用英文回答。"},
	{ID: "chinese", Name: "中文", Practice: "用中文回答。"},
	{ID: "bilingual", Name: "中英对照", Practice: "中文回答，关键术语第一次出现时附英文。"},
	{ID: "bullets", Name: "列表", Practice: "用列表，不用长段落。"},
	{ID: "steps", Name: "步骤", Practice: "用有序步骤，一步一件事。"},
	{ID: "checklist", Name: "核对表", Practice: "只给可核对的完成标准。"},
	{ID: "faq", Name: "逐条问答", Practice: "按问题逐条回答。"},
	{ID: "glossary", Name: "先定义", Practice: "先定义回答里会用到的术语。"},
	{ID: "compare", Name: "对照", Practice: "只对照已给出的方案，最后明确选一个。"},
	{ID: "plan-first", Name: "先计划", Practice: "先列出要改的文件和各自原因，再写代码。"},
	{ID: "patch-only", Name: "只给补丁", Practice: "只给要改的代码，不写背景。"},
	{ID: "code-heavy", Name: "多代码", Practice: "少写叙述，以代码为主。"},
	{ID: "no-code", Name: "少代码", Practice: "不贴大段代码，只讲判断和改动位置。"},
	{ID: "diff-narration", Name: "按文件说明", Practice: "按文件说明改了什么。"},
	{ID: "review", Name: "评审", Practice: "先写问题，再写建议，最后写不必改的部分。"},
	{ID: "debug", Name: "排障", Practice: "先写已看到的证据，再写结论；证据不足就写还缺什么。"},
	{ID: "test-first", Name: "先写测试", Practice: "先写应补的测试和失败条件。"},
	{ID: "qa", Name: "边界清单", Practice: "列出边界、失败情况和还没覆盖的输入。"},
	{ID: "commands", Name: "只给命令", Practice: "只给可复制的命令。"},
	{ID: "api-doc", Name: "接口文档", Practice: "按接口说明写：输入、输出、错误。"},
	{ID: "commit-msg", Name: "提交说明", Practice: "按提交说明写：为什么改，不是改了哪些行。"},
	{ID: "release-note", Name: "发布说明", Practice: "按使用者能看懂的变更说明写。"},
	{ID: "incident", Name: "事故记录", Practice: "按现象、原因、处理、还没确认的部分写。"},
	{ID: "oncall", Name: "先止损", Practice: "先给恢复或止损，再写原因。"},
	{ID: "migration", Name: "迁移", Practice: "按迁移步骤写，并写如何回滚。"},
	{ID: "spec", Name: "规格", Practice: "按输入、输出、约束、不做的事写。"},
	{ID: "security", Name: "安全", Practice: "只写安全影响和改法。"},
	{ID: "perf", Name: "性能", Practice: "只写性能影响；没有测量就不要给数字。"},
	{ID: "refactor", Name: "重构", Practice: "只写结构改动，不顺带加功能。"},
	{ID: "risk", Name: "先讲风险", Practice: "先写会破坏什么，再写做法。"},
	{ID: "warning-first", Name: "先说不要做", Practice: "先写不要做什么。"},
	{ID: "sources", Name: "标出处", Practice: "每个事实后面注明来自哪次工具结果或用户哪句话。"},
	{ID: "timeline", Name: "按时间", Practice: "按发生顺序写。"},
	{ID: "optimistic", Name: "先给活路", Practice: "先写一条走得通的路。"},
	{ID: "skeptical", Name: "先讲失败", Practice: "先写这个做法会在什么情况下失败。"},
}
