// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyDiffHunk(arg1, arg2, arg3) {
  return window['go']['main']['App']['ApplyDiffHunk'](arg1, arg2, arg3);
}

export function CancelAgentStream() {
  return window['go']['main']['App']['CancelAgentStream']();
}

export function CancelTerminalCommand() {
  return window['go']['main']['App']['CancelTerminalCommand']();
}

export function CloseWindow() {
  return window['go']['main']['App']['CloseWindow']();
}

export function DeleteChannel(arg1) {
  return window['go']['main']['App']['DeleteChannel'](arg1);
}

export function DeleteMCP(arg1) {
  return window['go']['main']['App']['DeleteMCP'](arg1);
}

export function DeleteRule(arg1) {
  return window['go']['main']['App']['DeleteRule'](arg1);
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function DeleteSkill(arg1) {
  return window['go']['main']['App']['DeleteSkill'](arg1);
}

export function DiagnoseFile(arg1) {
  return window['go']['main']['App']['DiagnoseFile'](arg1);
}

export function DiscardDiffHunk(arg1, arg2) {
  return window['go']['main']['App']['DiscardDiffHunk'](arg1, arg2);
}

export function ExecCommand(arg1) {
  return window['go']['main']['App']['ExecCommand'](arg1);
}

export function ExecTerminalStream(arg1) {
  return window['go']['main']['App']['ExecTerminalStream'](arg1);
}

export function FetchUpstreamModels(arg1, arg2) {
  return window['go']['main']['App']['FetchUpstreamModels'](arg1, arg2);
}

export function GetFileTree(arg1) {
  return window['go']['main']['App']['GetFileTree'](arg1);
}

export function GetGitStatus() {
  return window['go']['main']['App']['GetGitStatus']();
}

export function GetProjectASTGraph() {
  return window['go']['main']['App']['GetProjectASTGraph']();
}

export function GetSession(arg1) {
  return window['go']['main']['App']['GetSession'](arg1);
}

export function GetStructuredDiff(arg1) {
  return window['go']['main']['App']['GetStructuredDiff'](arg1);
}

export function GetUsageMetrics() {
  return window['go']['main']['App']['GetUsageMetrics']();
}

export function GetUIPrefs() {
  return window['go']['main']['App']['GetUIPrefs']();
}

export function SaveUIPrefs(arg1) {
  return window['go']['main']['App']['SaveUIPrefs'](arg1);
}

export function ImportWorkspaceRules() {
  return window['go']['main']['App']['ImportWorkspaceRules']();
}

export function GetSandboxStatus() {
  return window['go']['main']['App']['GetSandboxStatus']();
}

export function GetRuntimeInfo() {
  return window['go']['main']['App']['GetRuntimeInfo']();
}

export function ExportDiagnostics() {
  return window['go']['main']['App']['ExportDiagnostics']();
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function ListSkillTemplates() {
  return window['go']['main']['App']['ListSkillTemplates']();
}

export function InstallSkillTemplate(arg1) {
  return window['go']['main']['App']['InstallSkillTemplate'](arg1);
}

export function GetWorkspace() {
  return window['go']['main']['App']['GetWorkspace']();
}

export function GitCheckoutBranch(arg1) {
  return window['go']['main']['App']['GitCheckoutBranch'](arg1);
}

export function GitCommit(arg1) {
  return window['go']['main']['App']['GitCommit'](arg1);
}

export function GitCreateBranch(arg1) {
  return window['go']['main']['App']['GitCreateBranch'](arg1);
}

export function GitCreateSnapshot(arg1) {
  return window['go']['main']['App']['GitCreateSnapshot'](arg1);
}

export function GitListBranches() {
  return window['go']['main']['App']['GitListBranches']();
}

export function GitListSnapshots() {
  return window['go']['main']['App']['GitListSnapshots']();
}

export function GitRestoreSnapshot(arg1) {
  return window['go']['main']['App']['GitRestoreSnapshot'](arg1);
}

export function GitStage(arg1) {
  return window['go']['main']['App']['GitStage'](arg1);
}

export function GitUnstage(arg1) {
  return window['go']['main']['App']['GitUnstage'](arg1);
}

export function ListChannels() {
  return window['go']['main']['App']['ListChannels']();
}

export function ResumeAgentChoice(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ResumeAgentChoice'](arg1, arg2, arg3, arg4);
}

export function ResumeAgentConfirm(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResumeAgentConfirm'](arg1, arg2, arg3);
}

export function ListMCPs() {
  return window['go']['main']['App']['ListMCPs']();
}

export function ListRules() {
  return window['go']['main']['App']['ListRules']();
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function ListSkills() {
  return window['go']['main']['App']['ListSkills']();
}

export function MinimizeWindow() {
  return window['go']['main']['App']['MinimizeWindow']();
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function PingChannel(arg1) {
  return window['go']['main']['App']['PingChannel'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function RevertFile(arg1) {
  return window['go']['main']['App']['RevertFile'](arg1);
}

export function RunSecurityAudit() {
  return window['go']['main']['App']['RunSecurityAudit']();
}

export function RunTDDValidation() {
  return window['go']['main']['App']['RunTDDValidation']();
}

export function SaveChannel(arg1) {
  return window['go']['main']['App']['SaveChannel'](arg1);
}

export function SaveMCP(arg1) {
  return window['go']['main']['App']['SaveMCP'](arg1);
}

export function SaveRule(arg1) {
  return window['go']['main']['App']['SaveRule'](arg1);
}

export function SaveSession(arg1) {
  return window['go']['main']['App']['SaveSession'](arg1);
}

export function SaveSkill(arg1) {
  return window['go']['main']['App']['SaveSkill'](arg1);
}

export function SendMessage(arg1) {
  return window['go']['main']['App']['SendMessage'](arg1);
}

export function SetWorkspace(arg1) {
  return window['go']['main']['App']['SetWorkspace'](arg1);
}

export function TestMCPServer(arg1) {
  return window['go']['main']['App']['TestMCPServer'](arg1);
}

export function ToggleMaximizeWindow() {
  return window['go']['main']['App']['ToggleMaximizeWindow']();
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2);
}

export function GetHotplugDashboard() {
  return window['go']['main']['App']['GetHotplugDashboard']();
}

export function ReloadHotplugRegistry() {
  return window['go']['main']['App']['ReloadHotplugRegistry']();
}

export function ProbeHotplugItem(arg1, arg2) {
  return window['go']['main']['App']['ProbeHotplugItem'](arg1, arg2);
}

export function ExportHotplugManifest() {
  return window['go']['main']['App']['ExportHotplugManifest']();
}
