// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {lsp} from '../models';
import {main} from '../models';
import {ast} from '../models';
import {session} from '../models';
import {diff} from '../models';
import {telemetry} from '../models';
import {gitops} from '../models';
import {config} from '../models';
import {agent} from '../models';
import {mcp} from '../models';

export function ApplyDiffHunk(arg1:string,arg2:number,arg3:boolean):Promise<void>;

export function CancelAgentStream():Promise<void>;

export function CancelTerminalCommand():Promise<void>;

export function CloseWindow():Promise<void>;

export function DeleteChannel(arg1:string):Promise<void>;

export function DeleteMCP(arg1:string):Promise<void>;

export function DeleteRule(arg1:string):Promise<void>;

export function DeleteSession(arg1:string):Promise<void>;

export function DeleteSkill(arg1:string):Promise<void>;

export function DiagnoseFile(arg1:string):Promise<lsp.DiagnosticReport>;

export function DiscardDiffHunk(arg1:string,arg2:number):Promise<void>;

export function ExecCommand(arg1:string):Promise<string>;

export function ExecTerminalStream(arg1:string):Promise<void>;

export function FetchUpstreamModels(arg1:string,arg2:string):Promise<Array<string>>;

export function GetFileTree(arg1:string):Promise<Array<main.FileNode>>;

export function GetGitStatus():Promise<{[key: string]: any}>;

export function GetProjectASTGraph():Promise<Array<ast.GraphNode>>;

export function GetSession(arg1:string):Promise<session.ChatSession>;

export function GetStructuredDiff(arg1:string):Promise<diff.DiffReport>;

export function GetUsageMetrics():Promise<telemetry.UsageMetrics>;

export function GetUIPrefs():Promise<config.UIPrefs>;
export function SaveUIPrefs(arg1:config.UIPrefs):Promise<void>;
export function ResumeAgentChoice(arg1:string,arg2:string,arg3:string,arg4:string):Promise<boolean>;
export function ResumeAgentConfirm(arg1:string,arg2:string,arg3:boolean):Promise<boolean>;
export function ImportWorkspaceRules():Promise<number>;
export function GetSandboxStatus():Promise<main.SandboxStatus>;
export function GetRuntimeInfo():Promise<main.RuntimeInfo>;
export function ExportDiagnostics():Promise<string>;
export function CheckForUpdates():Promise<string>;
export function ListSkillTemplates():Promise<Array<config.SkillConfig>>;
export function InstallSkillTemplate(arg1:string):Promise<void>;
export function GetWorkspace():Promise<string>;

export function GitCheckoutBranch(arg1:string):Promise<void>;

export function GitCommit(arg1:string):Promise<string>;

export function GitCreateBranch(arg1:string):Promise<void>;

export function GitCreateSnapshot(arg1:string):Promise<void>;

export function GitListBranches():Promise<Array<string>>;

export function GitListSnapshots():Promise<Array<gitops.Snapshot>>;

export function GitRestoreSnapshot(arg1:string):Promise<void>;

export function GitStage(arg1:string):Promise<void>;

export function GitUnstage(arg1:string):Promise<void>;

export function ListChannels():Promise<Array<config.ChannelConfig>>;

export function ResumeAgentChoice(arg1:string,arg2:string,arg3:string,arg4:string):Promise<boolean>;

export function ListMCPs():Promise<Array<config.MCPServerConfig>>;

export function ListRules():Promise<Array<config.RuleConfig>>;

export function ListSessions():Promise<Array<session.SessionMeta>>;

export function ListSkills():Promise<Array<config.SkillConfig>>;

export function MinimizeWindow():Promise<void>;

export function OpenDirectoryDialog():Promise<string>;

export function OpenFileDialog():Promise<Array<string>>;

export function PingChannel(arg1:string):Promise<string>;

export function ReadFile(arg1:string):Promise<string>;

export function RevertFile(arg1:string):Promise<void>;

export function RunSecurityAudit():Promise<agent.AuditReport>;

export function RunTDDValidation():Promise<agent.TestReport>;

export function SaveChannel(arg1:config.ChannelConfig):Promise<void>;

export function SaveMCP(arg1:config.MCPServerConfig):Promise<void>;

export function SaveRule(arg1:config.RuleConfig):Promise<void>;

export function SaveSession(arg1:session.ChatSession):Promise<void>;

export function SaveSkill(arg1:config.SkillConfig):Promise<void>;

export function SendMessage(arg1:main.ChatRequest):Promise<void>;

export function SetWorkspace(arg1:string):Promise<void>;

export function TestMCPServer(arg1:string):Promise<mcp.MCPTestResult>;

export function ToggleMaximizeWindow():Promise<void>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;

export function GetHotplugDashboard():Promise<any>;

export function ReloadHotplugRegistry():Promise<any>;

export function ProbeHotplugItem(arg1:string,arg2:string):Promise<any>;

export function ExportHotplugManifest():Promise<string>;
